// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP6rZ9RlR-ENLuhIg1ItMQMbrEv5rQX9k',
    appId: '1:360795635337:web:e9eafcdaa33b23b9001058',
    messagingSenderId: '360795635337',
    projectId: 'cafeflow-5tg',
    authDomain: 'cafeflow-5tg.firebaseapp.com',
    storageBucket: 'cafeflow-5tg.firebasestorage.app',
    measurementId: 'G-5R86Q6H7W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmqEMM5SgYQu2N9FJmx5po6q9TP0TUhv8',
    appId: '1:360795635337:android:408e1e9877563003001058',
    messagingSenderId: '360795635337',
    projectId: 'cafeflow-5tg',
    storageBucket: 'cafeflow-5tg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQfhV4C1omQlBSBoEShf0LJ9dk1tO7dnU',
    appId: '1:360795635337:ios:b9b9b2a02ed0539a001058',
    messagingSenderId: '360795635337',
    projectId: 'cafeflow-5tg',
    storageBucket: 'cafeflow-5tg.firebasestorage.app',
    iosBundleId: 'com.fivetogo.fivetogoScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQfhV4C1omQlBSBoEShf0LJ9dk1tO7dnU',
    appId: '1:360795635337:ios:b9b9b2a02ed0539a001058',
    messagingSenderId: '360795635337',
    projectId: 'cafeflow-5tg',
    storageBucket: 'cafeflow-5tg.firebasestorage.app',
    iosBundleId: 'com.fivetogo.fivetogoScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP6rZ9RlR-ENLuhIg1ItMQMbrEv5rQX9k',
    appId: '1:360795635337:web:7d6099d8e8e9f421001058',
    messagingSenderId: '360795635337',
    projectId: 'cafeflow-5tg',
    authDomain: 'cafeflow-5tg.firebaseapp.com',
    storageBucket: 'cafeflow-5tg.firebasestorage.app',
    measurementId: 'G-TS3YTZ6XSJ',
  );
}
